source "https://rubygems.org"

gem "capybara", "3.35"
gem "cucumber", "6.1"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.9"
gem "httparty", "0.18.1"
gem "rufo", "0.12.0"
gem "allure-cucumber", "2.13.10"
